SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
IF  EXISTS (select * FROM sys.views where name = 'View_User') 
	BEGIN
	DROP VIEW [dbo].[View_User]
	END
GO
CREATE view [dbo].[View_User]
	as
	SELECT EMPN_PSL AS Id, NAME_PSL AS 'Name', PSWD_PSW as Password
	FROM dbo.PERSONEL p
	INNER JOIN dbo.PASSWRD pw ON p.EMPN_PSL = pw.EMPN_PSW
GO

IF NOT EXISTS (SELECT * FROM SYSOBJECTS WHERE NAME='Permission' AND XTYPE='U')
CREATE TABLE [dbo].[Mobile_Permission](
	  Id INT NOT NULL IDENTITY  PRIMARY KEY,
	  Code NVARCHAR(100) NOT NULL,
	  Label NVARCHAR(100)
)
GO
IF NOT EXISTS (SELECT * FROM SYSOBJECTS WHERE NAME='User_Permission' AND XTYPE='U')
CREATE TABLE [dbo].[Mobile_User_Permission](
	  Id INT NOT NULL IDENTITY  PRIMARY KEY,
	  UserId NVARCHAR(4) NOT NULL,
	  PermissionId INT NOT NULL
)
GO
	

