using System;
using System.Collections.Generic;

namespace LjData.Models
{
    public partial class Colorpalette
    {
        public string DocnClp { get; set; }
        public DateTime? DateClp { get; set; }
        public DateTime? CrtdClp { get; set; }
        public string ToClp { get; set; }
        public string FwlrClp { get; set; }
        public string SendClp { get; set; }
        public string ReqdClp { get; set; }
        public string DsgyClp { get; set; }
        public string XswayClp { get; set; }
        public string ClrnClp { get; set; }
        public string PnnbClp { get; set; }
        public string CstmClp { get; set; }
        public string RswayClp { get; set; }
        public string SizeClp { get; set; }
        public string MtlClp { get; set; }
        public string SpecClp { get; set; }
        public string Rmk1Clp { get; set; }
        public string Rmk2Clp { get; set; }
        public string MakrClp { get; set; }
        public string ChkrClp { get; set; }
        public bool? CmplClp { get; set; }
        public bool? SealClp { get; set; }
        public int? PcntClp { get; set; }
        public DateTime? LdatClp { get; set; }
        public string LedtClp { get; set; }
        public int? Clr1rClp { get; set; }
        public int? Clr1gClp { get; set; }
        public int? Clr1bClp { get; set; }
        public string Clr1n1Clp { get; set; }
        public string Clr1b1cClp { get; set; }
        public string Clr1b1vClp { get; set; }
        public string Clr1b2cClp { get; set; }
        public string Clr1b2vClp { get; set; }
        public string Clr1xscClp { get; set; }
        public string Clr1xsClp { get; set; }
        public string Clr1zscClp { get; set; }
        public string Clr1zsClp { get; set; }
        public string Clr1gccClp { get; set; }
        public string Clr1gcClp { get; set; }
        public string Clr1sccClp { get; set; }
        public string Clr1scClp { get; set; }
        public string Clr1rscClp { get; set; }
        public string Clr1rsClp { get; set; }
        public string Clr1ylcClp { get; set; }
        public string Clr1ylClp { get; set; }
        public string Clr1sljcClp { get; set; }
        public string Clr1sljClp { get; set; }
        public string Clr1slwcClp { get; set; }
        public string Clr1slwClp { get; set; }
        public int? Clr2rClp { get; set; }
        public int? Clr2gClp { get; set; }
        public int? Clr2bClp { get; set; }
        public string Clr2n1Clp { get; set; }
        public string Clr2b1cClp { get; set; }
        public string Clr2b1vClp { get; set; }
        public string Clr2b2cClp { get; set; }
        public string Clr2b2vClp { get; set; }
        public string Clr2xscClp { get; set; }
        public string Clr2xsClp { get; set; }
        public string Clr2zscClp { get; set; }
        public string Clr2zsClp { get; set; }
        public string Clr2gccClp { get; set; }
        public string Clr2gcClp { get; set; }
        public string Clr2sccClp { get; set; }
        public string Clr2scClp { get; set; }
        public string Clr2rscClp { get; set; }
        public string Clr2rsClp { get; set; }
        public string Clr2ylcClp { get; set; }
        public string Clr2ylClp { get; set; }
        public string Clr2sljcClp { get; set; }
        public string Clr2sljClp { get; set; }
        public string Clr2slwcClp { get; set; }
        public string Clr2slwClp { get; set; }
        public int? Clr3rClp { get; set; }
        public int? Clr3gClp { get; set; }
        public int? Clr3bClp { get; set; }
        public string Clr3n1Clp { get; set; }
        public string Clr3b1cClp { get; set; }
        public string Clr3b1vClp { get; set; }
        public string Clr3b2cClp { get; set; }
        public string Clr3b2vClp { get; set; }
        public string Clr3xscClp { get; set; }
        public string Clr3xsClp { get; set; }
        public string Clr3zscClp { get; set; }
        public string Clr3zsClp { get; set; }
        public string Clr3gccClp { get; set; }
        public string Clr3gcClp { get; set; }
        public string Clr3sccClp { get; set; }
        public string Clr3scClp { get; set; }
        public string Clr3rscClp { get; set; }
        public string Clr3rsClp { get; set; }
        public string Clr3ylcClp { get; set; }
        public string Clr3ylClp { get; set; }
        public string Clr3sljcClp { get; set; }
        public string Clr3sljClp { get; set; }
        public string Clr3slwcClp { get; set; }
        public string Clr3slwClp { get; set; }
        public int? Clr4rClp { get; set; }
        public int? Clr4gClp { get; set; }
        public int? Clr4bClp { get; set; }
        public string Clr4n1Clp { get; set; }
        public string Clr4b1cClp { get; set; }
        public string Clr4b1vClp { get; set; }
        public string Clr4b2cClp { get; set; }
        public string Clr4b2vClp { get; set; }
        public string Clr4xscClp { get; set; }
        public string Clr4xsClp { get; set; }
        public string Clr4zscClp { get; set; }
        public string Clr4zsClp { get; set; }
        public string Clr4gccClp { get; set; }
        public string Clr4gcClp { get; set; }
        public string Clr4sccClp { get; set; }
        public string Clr4scClp { get; set; }
        public string Clr4rscClp { get; set; }
        public string Clr4rsClp { get; set; }
        public string Clr4ylcClp { get; set; }
        public string Clr4ylClp { get; set; }
        public string Clr4sljcClp { get; set; }
        public string Clr4sljClp { get; set; }
        public string Clr4slwcClp { get; set; }
        public string Clr4slwClp { get; set; }
        public int? Clr5rClp { get; set; }
        public int? Clr5gClp { get; set; }
        public int? Clr5bClp { get; set; }
        public string Clr5n1Clp { get; set; }
        public string Clr5b1cClp { get; set; }
        public string Clr5b1vClp { get; set; }
        public string Clr5b2cClp { get; set; }
        public string Clr5b2vClp { get; set; }
        public string Clr5xscClp { get; set; }
        public string Clr5xsClp { get; set; }
        public string Clr5zscClp { get; set; }
        public string Clr5zsClp { get; set; }
        public string Clr5gccClp { get; set; }
        public string Clr5gcClp { get; set; }
        public string Clr5sccClp { get; set; }
        public string Clr5scClp { get; set; }
        public string Clr5rscClp { get; set; }
        public string Clr5rsClp { get; set; }
        public string Clr5ylcClp { get; set; }
        public string Clr5ylClp { get; set; }
        public string Clr5sljcClp { get; set; }
        public string Clr5sljClp { get; set; }
        public string Clr5slwcClp { get; set; }
        public string Clr5slwClp { get; set; }
        public int? Clr6rClp { get; set; }
        public int? Clr6gClp { get; set; }
        public int? Clr6bClp { get; set; }
        public string Clr6n1Clp { get; set; }
        public string Clr6b1cClp { get; set; }
        public string Clr6b1vClp { get; set; }
        public string Clr6b2cClp { get; set; }
        public string Clr6b2vClp { get; set; }
        public string Clr6xscClp { get; set; }
        public string Clr6xsClp { get; set; }
        public string Clr6zscClp { get; set; }
        public string Clr6zsClp { get; set; }
        public string Clr6gccClp { get; set; }
        public string Clr6gcClp { get; set; }
        public string Clr6sccClp { get; set; }
        public string Clr6scClp { get; set; }
        public string Clr6rscClp { get; set; }
        public string Clr6rsClp { get; set; }
        public string Clr6ylcClp { get; set; }
        public string Clr6ylClp { get; set; }
        public string Clr6sljcClp { get; set; }
        public string Clr6sljClp { get; set; }
        public string Clr6slwcClp { get; set; }
        public string Clr6slwClp { get; set; }
        public int? Clr7rClp { get; set; }
        public int? Clr7gClp { get; set; }
        public int? Clr7bClp { get; set; }
        public string Clr7n1Clp { get; set; }
        public string Clr7b1cClp { get; set; }
        public string Clr7b1vClp { get; set; }
        public string Clr7b2cClp { get; set; }
        public string Clr7b2vClp { get; set; }
        public string Clr7xscClp { get; set; }
        public string Clr7xsClp { get; set; }
        public string Clr7zscClp { get; set; }
        public string Clr7zsClp { get; set; }
        public string Clr7gccClp { get; set; }
        public string Clr7gcClp { get; set; }
        public string Clr7sccClp { get; set; }
        public string Clr7scClp { get; set; }
        public string Clr7rscClp { get; set; }
        public string Clr7rsClp { get; set; }
        public string Clr7ylcClp { get; set; }
        public string Clr7ylClp { get; set; }
        public string Clr7sljcClp { get; set; }
        public string Clr7sljClp { get; set; }
        public string Clr7slwcClp { get; set; }
        public string Clr7slwClp { get; set; }
        public int? Clr8rClp { get; set; }
        public int? Clr8gClp { get; set; }
        public int? Clr8bClp { get; set; }
        public string Clr8n1Clp { get; set; }
        public string Clr8b1cClp { get; set; }
        public string Clr8b1vClp { get; set; }
        public string Clr8b2cClp { get; set; }
        public string Clr8b2vClp { get; set; }
        public string Clr8xscClp { get; set; }
        public string Clr8xsClp { get; set; }
        public string Clr8zscClp { get; set; }
        public string Clr8zsClp { get; set; }
        public string Clr8gccClp { get; set; }
        public string Clr8gcClp { get; set; }
        public string Clr8sccClp { get; set; }
        public string Clr8scClp { get; set; }
        public string Clr8rscClp { get; set; }
        public string Clr8rsClp { get; set; }
        public string Clr8ylcClp { get; set; }
        public string Clr8ylClp { get; set; }
        public string Clr8sljcClp { get; set; }
        public string Clr8sljClp { get; set; }
        public string Clr8slwcClp { get; set; }
        public string Clr8slwClp { get; set; }
        public string MrmkClp { get; set; }
        public string CachetClp { get; set; }
        public string PlntClp { get; set; }
    }
}
