using System;
using System.Collections.Generic;

namespace LjData.Models
{
    public partial class DeclareO
    {
        public string FmnoDo { get; set; }
        public DateTime? LdatDo { get; set; }
        public string LedtDo { get; set; }
        public string Fd01Do { get; set; }
        public string Fd02Do { get; set; }
        public string Fd03Do { get; set; }
        public string Fd03cDo { get; set; }
        public string Fd04Do { get; set; }
        public string Fd05Do { get; set; }
        public string Fd06Do { get; set; }
        public string Fd07Do { get; set; }
        public string Fd07cDo { get; set; }
        public string Fd08Do { get; set; }
        public string Fd09Do { get; set; }
        public string Fd10Do { get; set; }
        public string Fd11Do { get; set; }
        public string Fd11cDo { get; set; }
        public string Fd12Do { get; set; }
        public string Fd12cDo { get; set; }
        public string Fd13Do { get; set; }
        public string Fd13cDo { get; set; }
        public string Fd14Do { get; set; }
        public string Fd14cDo { get; set; }
        public string Fd15Do { get; set; }
        public string Fd16Do { get; set; }
        public string Fd16cDo { get; set; }
        public string Fd17Do { get; set; }
        public string Fd17cDo { get; set; }
        public string Fd18Do { get; set; }
        public string Fd18cDo { get; set; }
        public string Fd19Do { get; set; }
        public string Fd20Do { get; set; }
        public string Fd21Do { get; set; }
        public string Fd22Do { get; set; }
        public string Fd23Do { get; set; }
        public string Fd24Do { get; set; }
        public string Fd25Do { get; set; }
        public string Fd26Do { get; set; }
        public string Fd27Do { get; set; }
        public string Fd28Do { get; set; }
        public string Fd29Do { get; set; }
        public string Fd30Do { get; set; }
        public string Fd31Do { get; set; }
        public string Fd32Do { get; set; }
        public string Fd3311Do { get; set; }
        public string Fd3312Do { get; set; }
        public string Fd3313Do { get; set; }
        public string Fd3314Do { get; set; }
        public string Fd3315Do { get; set; }
        public string Fd3316Do { get; set; }
        public string Fd3317Do { get; set; }
        public string Fd3318Do { get; set; }
        public string Fd3319Do { get; set; }
        public string Fd3321Do { get; set; }
        public string Fd3322Do { get; set; }
        public string Fd3323Do { get; set; }
        public string Fd3324Do { get; set; }
        public string Fd3325Do { get; set; }
        public string Fd3326Do { get; set; }
        public string Fd3327Do { get; set; }
        public string Fd3328Do { get; set; }
        public string Fd3329Do { get; set; }
        public string Fd3331Do { get; set; }
        public string Fd3332Do { get; set; }
        public string Fd3333Do { get; set; }
        public string Fd3334Do { get; set; }
        public string Fd3335Do { get; set; }
        public string Fd3336Do { get; set; }
        public string Fd3337Do { get; set; }
        public string Fd3338Do { get; set; }
        public string Fd3339Do { get; set; }
        public string Fd3341Do { get; set; }
        public string Fd3342Do { get; set; }
        public string Fd3343Do { get; set; }
        public string Fd3344Do { get; set; }
        public string Fd3345Do { get; set; }
        public string Fd3346Do { get; set; }
        public string Fd3347Do { get; set; }
        public string Fd3348Do { get; set; }
        public string Fd3349Do { get; set; }
        public string Fd3351Do { get; set; }
        public string Fd3352Do { get; set; }
        public string Fd3353Do { get; set; }
        public string Fd3354Do { get; set; }
        public string Fd3355Do { get; set; }
        public string Fd3356Do { get; set; }
        public string Fd3357Do { get; set; }
        public string Fd3358Do { get; set; }
        public string Fd3359Do { get; set; }
        public string Fd3361Do { get; set; }
        public string Fd3362Do { get; set; }
        public string Fd3363Do { get; set; }
        public string Fd3364Do { get; set; }
        public string Fd3365Do { get; set; }
        public string Fd3366Do { get; set; }
        public string Fd3367Do { get; set; }
        public string Fd3368Do { get; set; }
        public string Fd3369Do { get; set; }
        public string Fd3371Do { get; set; }
        public string Fd3372Do { get; set; }
        public string Fd3373Do { get; set; }
        public string Fd3374Do { get; set; }
        public string Fd3375Do { get; set; }
        public string Fd3376Do { get; set; }
        public string Fd3377Do { get; set; }
        public string Fd3378Do { get; set; }
        public string Fd3379Do { get; set; }
        public string Fd3381Do { get; set; }
        public string Fd3382Do { get; set; }
        public string Fd3383Do { get; set; }
        public string Fd3384Do { get; set; }
        public string Fd3385Do { get; set; }
        public string Fd3386Do { get; set; }
        public string Fd3387Do { get; set; }
        public string Fd3388Do { get; set; }
        public string Fd3389Do { get; set; }
        public string Fd3391Do { get; set; }
        public string Fd3392Do { get; set; }
        public string Fd3393Do { get; set; }
        public string Fd3394Do { get; set; }
        public string Fd3395Do { get; set; }
        public string Fd3396Do { get; set; }
        public string Fd3397Do { get; set; }
        public string Fd3398Do { get; set; }
        public string Fd3399Do { get; set; }
        public string Fd33A1Do { get; set; }
        public string Fd33A2Do { get; set; }
        public string Fd33A3Do { get; set; }
        public string Fd33A4Do { get; set; }
        public string Fd33A5Do { get; set; }
        public string Fd33A6Do { get; set; }
        public string Fd33A7Do { get; set; }
        public string Fd33A8Do { get; set; }
        public string Fd33A9Do { get; set; }
        public string Fd33B1Do { get; set; }
        public string Fd33B2Do { get; set; }
        public string Fd33B3Do { get; set; }
        public string Fd33B4Do { get; set; }
        public string Fd33B5Do { get; set; }
        public string Fd33B6Do { get; set; }
        public string Fd33B7Do { get; set; }
        public string Fd33B8Do { get; set; }
        public string Fd33B9Do { get; set; }
        public string Fd33C1Do { get; set; }
        public string Fd33C2Do { get; set; }
        public string Fd33C3Do { get; set; }
        public string Fd33C4Do { get; set; }
        public string Fd33C5Do { get; set; }
        public string Fd33C6Do { get; set; }
        public string Fd33C7Do { get; set; }
        public string Fd33C8Do { get; set; }
        public string Fd33C9Do { get; set; }
        public string Fd33D1Do { get; set; }
        public string Fd33D2Do { get; set; }
        public string Fd33D3Do { get; set; }
        public string Fd33D4Do { get; set; }
        public string Fd33D5Do { get; set; }
        public string Fd33D6Do { get; set; }
        public string Fd33D7Do { get; set; }
        public string Fd33D8Do { get; set; }
        public string Fd33D9Do { get; set; }
        public string Fd33E1Do { get; set; }
        public string Fd33E2Do { get; set; }
        public string Fd33E3Do { get; set; }
        public string Fd33E4Do { get; set; }
        public string Fd33E5Do { get; set; }
        public string Fd33E6Do { get; set; }
        public string Fd33E7Do { get; set; }
        public string Fd33E8Do { get; set; }
        public string Fd33E9Do { get; set; }
        public string Fd33F1Do { get; set; }
        public string Fd33F2Do { get; set; }
        public string Fd33F3Do { get; set; }
        public string Fd33F4Do { get; set; }
        public string Fd33F5Do { get; set; }
        public string Fd33F6Do { get; set; }
        public string Fd33F7Do { get; set; }
        public string Fd33F8Do { get; set; }
        public string Fd33F9Do { get; set; }
        public string Fd34Do { get; set; }
        public string Fd35Do { get; set; }
        public string Fd36Do { get; set; }
        public string Fd37Do { get; set; }
        public string Fd38Do { get; set; }
        public string Fd39Do { get; set; }
        public string Fd40Do { get; set; }
        public string Fd41Do { get; set; }
        public string Fd42Do { get; set; }
        public string Fd43Do { get; set; }
        public string Fd44Do { get; set; }
        public string Fd45Do { get; set; }
        public string Fd46Do { get; set; }
        public string Fd47Do { get; set; }
        public string PlntDo { get; set; }
    }
}
